from datetime import date
from typing import List, Optional
from pydantic import BaseModel, Field


class BusinessProfile(BaseModel):
    """
    Captures the enterprise metadata required to calculate 
    specific regulatory roadmaps based on industry and region.
    """
    business_name: str
    industry: str
    employee_count: int
    annual_turnover_kes: float
    years_in_operation: int
    county: str # e.g., "Nairobi", "Kakamega", "Kisumu"


class ComplianceItem(BaseModel):
    id: str
    title: str = "Unnamed Requirement"
    # Provide a default string to prevent "Field Required" errors
    description: str = "Standard regulatory requirement for business operations." 
    authority: str = "Government Authority"
    county: Optional[str] = "National"
    deadline: Optional[str] = None
    penalty: str = "Fines or legal action"
    status: str = "required"
    category: str = "General"
    priority: str = "medium"
    steps: List[str] = []
    links: List[str] = []


class DeadlineItem(BaseModel):
    """
    Specific model for tracking upcoming document expirations 
    and triggering multi-channel alerts.
    """
    title: str
    deadline: str
    authority: str
    days_left: int


class ComplianceReport(BaseModel):
    """
    The final audit report generated by the Knowledge Service, 
    calculating scores based on Vault contents.
    """
    business_name: str
    industry: str
    total_requirements: int
    high_priority: int
    compliance_score: int # Calculated as a % of high-priority documents found in the vault
    items: List[ComplianceItem]
    upcoming_deadlines: List[DeadlineItem]